SELECT 	
-- DATA, 
	MAX(DATA) ,
	CODIGO , MAX(PRECO), MAX(P_VP) , MIN(LIQUIDEZ_DIARIA), MIN(DY_MED_PERC), MIN(DY_ULT_VLR) ,MIN(ROE) ,MIN(PATRIMONIO_LUCRO) ,MIN(VALOR_MERCADO) 
	,MIN(PAYOUT) ,MAX(DIV_EBITIDA) ,MIN(EV_EBITIDA), MIN(MARGEM_LUCRO) ,MIN(PL) ,MIN(FII_QTDE_IMOVEIS) ,MAX(FII_VACANCIA)
FROM COTACOES_ACOES
WHERE 1=1
AND DATA >= '2024-04-28 00:41:24'
--AND CODIGO = 'ABCB4'
GROUP BY DATA, CODIGO
ORDER BY CODIGO, DATA DESC 
 
 
 